### ISSUE TITLE
🚀 [feature] 신고, 리뷰 등 팀 관련 API 및 전체적인 팀, 유저 검증 로직 개발 및 수정

### ISSUE THREAD

**Issue by sgn07124** [Teamingg/Backend#141]
# 🤖 기능 개요

## ✅ Todo
- [x] 팀장이 탈퇴 시, decisiondate(팀에 들어온 순서)가 가장 이른 팀원에게 양도되도록 수정
- [x] 팀 게시물 조회 API : Offset-based Pagination → Cursor-based Pagination 으로 수정 (무한스크롤 적용)
- [x] 탈퇴한 팀원 및 팀장은 팀에 접근 못하도록 수정
- [x] SecurityConfig 수정
  - [x] hasRole("USER") 삭제 
  - [x] cors 중복 코드 제거
- [x] ```/project/post/{project_id}/{post_id}``` → ```/project/post/{post_id}``` 로 수정
  - [x] 응답 데이터에  추가
- [x] ```/project/post/{post_id}``` 조회 시, 수정 권한이 없는 회원(쿠키 토큰 x)이면 canEdit 값을 false로 설정하고, 팀원(쿠키 토큰 o)이면 true로 설정하여 게시글 수정에 필요한 권한 조회 기능 추가
- [x] ```/project/post/{post_id}``` 조회 시, 유저가 해당 팀에 신청 여부를 반환하는 값을 추가. decisionDate 값 여부로 판단하며 null인 경우 신청 상태이므로 true 반환
