### ISSUE TITLE
🚀 [feature] 유저관련 API

### ISSUE THREAD

**Issue by minseo003** [Teamingg/Backend#55]
# 🤖 기능 개요
유저 수정기능과 경고횟수 조회 기능을 구현한다.
## ✅ Todo
- [x] 유저 이름 수정 API
- [x] 유저 포트폴리오 수정 API
- [x] 유저 경고횟수 조회API

### 📚 Remarks
서비스단에 transaction적용
PortfolioService,UserService 통합테스트 실행
user에 dto변환 메서드 추가(사용자 정보 조회API에적용해 코드변경)
