### ISSUE TITLE
🚀 [feature] 소셜로그인 토큰 전달 방식 변경

### ISSUE THREAD

**Issue by sgn07124** [Teamingg/Backend#67]
# 🤖 기능 개요

현재의 토큰 전달 방식은 쿼리 스트링에 토큰을 포함해서 넘기는 방식으로 보안 이슈가 있다.
따라서 HttpOnly 쿠키 전달 방식을 사용하도록 수정한다.

## ✅ Todo
- [x] 로그인 시, 토큰 전달 방식 수정
- [x] 인증 시, 쿠키에서 토큰을 추출할 수 있도록 수정
- [x] 토큰 만료 시, 재발급 로직 수정
- [x] 로그아웃 처리 로직 수정

**Comment by sgn07124** [comment]
## 문제 상황

현재 소셜 로그인을 서버에서 하고 있고, 로컬에서 개발할 때는 소셜 로그인을 진행 후 쿠키로 토큰을 받아 테스트를 진행 중이다.
프론트엔드에서 로컬 환경에서 개발을 위해 로그인 진행 시, 서버 주소와 localhost와 도메인이 달라 쿠키가 공유되지 않는다.

## 해결 과정

프론트엔드의 로컬 주소인 ``localhost:3000``을 pc 자체에서 localhost를 ``front.서버도메인 ``으로 수정하였다.
그리고 sameSite 설정을 ``sameSite("None")``으로 설정하여 교차 출처 요청을 허용하고, domain(``도메인``)을 추가하여 서브 도메인에서도 접근을 허용하도록 하였다.
또한 secure 설정을 ``secure(true)``로 하여 https에서만 쿠키가 공유되도록 설정하였다.
