### ISSUE TITLE
🚀 [feature] 엔티티 수정

### ISSUE THREAD

**Issue by minseo003** [Teamingg/Backend#87]
# 🤖 기능 개요
프로젝트쪽 엔티티에 개발스택,팀 개발스택, 유저 개발스택, 모집구분, 팀 모집구분 추가
멘토링쪽 엔티티에 카테고리, 팀 카테고리 추가

## ✅ Todo
- [x] 개발스택, 팀개발스택, 유저개발스택 추가, 매핑
- [x] 모집 구분, 팀 모집구분 추가, 매핑
- [x] 카테고리,팀 카테고리 추가, 매핑

### 📚 Remarks
