### ISSUE TITLE
🚀 [feature] 사용자 정보 관련 API

### ISSUE THREAD

**Issue by sgn07124** [Teamingg/Backend#96]
# 🤖 기능 개요

변경된 로직과 ERD를 반영하여 추가정보 저장 Api와 포트폴리오 관련 Api들을 수정

## ✅ Todo
- [x] 추가정보 입력 Api
- [x] 회원 정보 조회 Api
- [x] 개인정보 수정 Api
- [x] 기술 스택 수정 Api
